import type {
  Contact,
  Education,
  Experience,
  Profile,
  Project,
  SkillGroup,
  SuggestedSearch,
} from '../types/portfolio'

export const profile: Profile = {
  name: 'Rainner Yobelgates Franceisten Nainggolan',
  shortName: 'Rainner',
  role: 'Software Engineer',
  headline: 'Developer × Problem solver × Lifelong learner',
  summary:
    'Web developer and software engineer with a strong interest in application development and technology. A structured problem solver and fast learner, focused on building digital solutions that support users and business needs.',
  location: 'Pasar Rebo, East Jakarta, Indonesia',
  locationShort: 'East Jakarta, ID',
  languages: ['Indonesian', 'English'],
  image: null,
  resumeUrl: '/asssets/Rainner_Yobelgates_CV_EN.pdf',
  availability: null,
}
export const contact: Contact = {
  email: 'ryfranceisten@gmail.com',
  location: profile.location,
  phone: '0821 2359 5108',
  whatsAppNumber: '6282123595108',
  instagramUrl: 'https://www.instagram.com/rainner__yobelgates?stkn=MXI1Nmx0YWszcmZibQ==',
  instagramHandle: '@rainner__yobelgates',
  githubUrl: 'https://github.com/Rainner-yobelgates',
  githubHandle: 'Rainner-yobelgates',
  linkedinUrl: 'https://www.linkedin.com/in/rainner-yobelgates-286554214/',
  linkedinName: 'Rainner Yobelgates',
}
export const education: Education = {
  school: 'SMK Prestasi Prima',
  field: 'Software Engineering',
  period: '2019 — 2022',
  highlights: ['KKSI', 'Markoding', 'LSP certificate', 'Personal and freelance projects'],
}
export const skillGroups: SkillGroup[] = [
  {
    id: 'languages',
    title: 'Programming languages',
    icon: 'code',
    skills: ['HTML', 'CSS', 'JavaScript', 'TypeScript', 'PHP', 'Python'],
  },
  {
    id: 'frameworks',
    title: 'Frameworks & libraries',
    icon: 'layers',
    skills: ['Laravel', 'NestJS', 'Vue.js', 'React.js', 'Next.js'],
  },
  {
    id: 'tools',
    title: 'UI & development tools',
    icon: 'pen',
    skills: ['Tailwind CSS', 'Bootstrap', 'Sass', 'Figma'],
  },
  {
    id: 'databases',
    title: 'Databases & version control',
    icon: 'database',
    skills: ['MySQL', 'MongoDB', 'PostgreSQL', 'Git'],
  },
  {
    id: 'ai',
    title: 'AI-assisted development',
    icon: 'spark',
    skills: ['AI-assisted Software Development & Debugging', 'Prompt Engineering'],
  },
]
const missingAssets = {
  image: null,
  gallery: [],
  liveUrl: null,
  repositoryUrl: null,
  technologies: [],
  status: 'placeholder' as const,
}
export const projects: Project[] = [
  {
    ...missingAssets,
    slug: 'acs',
    title: 'ACS',
    shortLabel: 'ACS',
    category: 'Professional',
    company: 'PT Kolink Network Solution',
    summary:
      'Attendance system and device integration, connecting attendance workflows with ZKTeco and UBio devices.',
    features: ['Attendance system', 'ZKTeco / UBio device integration'],
    responsibilities: [
      'Implementation and troubleshooting',
      'Client technical support',
      'Thailand assignment for technical support and direct coordination with Group / Thai Oil',
    ],
    keywords: ['attendance', 'ZKTeco', 'UBio', 'Thailand', 'integration'],
    featured: true,
  },
  {
    ...missingAssets,
    slug: 'warehouse-management-system',
    title: 'Warehouse Management System',
    shortLabel: 'WMS',
    category: 'Professional',
    company: 'PT Kolink Network Solution',
    summary:
      'A warehouse system supporting products, stock, goods movement, and storage location management.',
    features: [
      'Product management',
      'Stock management',
      'Goods movement',
      'Storage location management',
    ],
    responsibilities: [],
    keywords: ['WMS', 'warehouse', 'inventory', 'stock'],
    featured: true,
  },
  {
    ...missingAssets,
    slug: 'ecovia',
    title: 'Ecovia',
    shortLabel: 'ECO',
    category: 'Professional',
    company: 'PT Kolink Network Solution',
    summary:
      'A location-based platform for discovering destinations, place information, reviews, and community content.',
    features: [
      'Destination discovery',
      'Place information',
      'Reviews and ratings',
      'Community content',
    ],
    responsibilities: [],
    keywords: ['location', 'destinations', 'platform', 'community'],
    featured: true,
  },
  {
    ...missingAssets,
    slug: 'stylease',
    title: 'Stylease',
    shortLabel: 'STY',
    category: 'Professional',
    company: 'PT Satu Visi Digital',
    summary:
      'A branded clothing rental platform with subscription, borrowing, and inventory flows.',
    features: ['Subscriptions', 'Clothing borrowing', 'Inventory management'],
    responsibilities: [],
    keywords: ['fashion', 'rental', 'clothing', 'subscription'],
    featured: false,
  },
  {
    ...missingAssets,
    slug: 'freelance-ecommerce',
    title: 'Freelance E-Commerce',
    shortLabel: 'ECM',
    category: 'Freelance',
    company: 'Freelance',
    summary:
      'Client e-commerce website development. Further project details will be added when available.',
    features: [],
    responsibilities: [],
    keywords: ['ecommerce', 'e-commerce', 'client', 'website'],
    featured: false,
  },
  {
    ...missingAssets,
    slug: 'optical-store-system',
    title: 'Optical Store System',
    shortLabel: 'OPT',
    category: 'Freelance',
    company: 'Freelance',
    summary:
      'A sales system for an optical store. Further project details will be added when available.',
    features: [],
    responsibilities: [],
    keywords: ['optical', 'sales', 'store'],
    featured: false,
  },
  {
    ...missingAssets,
    slug: 'travel-bus-reservation',
    title: 'Travel / Bus Reservation System',
    shortLabel: 'BUS',
    category: 'Freelance',
    company: 'Freelance',
    summary:
      'A travel and bus reservation system. Further project details will be added when available.',
    features: [],
    responsibilities: [],
    keywords: ['travel', 'bus', 'reservation'],
    featured: false,
  },
  {
    ...missingAssets,
    slug: 'galeri-sby-ani-library',
    title: 'Galeri SBY-ANI Library Website',
    shortLabel: 'LIB',
    category: 'Professional',
    company: 'PT Satu Visi Digital',
    summary: 'A book-data management website for Galeri SBY-ANI Library in Pacitan.',
    features: ['Book data management'],
    responsibilities: ['Technical support', 'Troubleshooting during data entry'],
    keywords: ['library', 'book', 'Pacitan'],
    featured: false,
  },
  {
    ...missingAssets,
    slug: 'tourism-profile-website',
    title: 'Tourism Profile Website',
    shortLabel: 'TRV',
    category: 'Internship',
    company: 'PT Industri Telekomunikasi Indonesia',
    summary: 'A tourism profile website developed during a web development internship.',
    features: [],
    responsibilities: [],
    keywords: ['tourism', 'internship', 'profile'],
    featured: false,
  },
]
export const experience: Experience[] = [
  {
    id: 'kolink',
    role: 'Software Engineer',
    company: 'PT Kolink Network Solution',
    period: 'April 2025 — Present',
    current: true,
    responsibilities: [
      'Attendance system implementation and ZKTeco / UBio device integration.',
      'Troubleshooting and client support.',
      'Thailand assignment for technical support and direct coordination with Group / Thai Oil.',
    ],
    projectSlugs: ['acs', 'warehouse-management-system', 'ecovia'],
  },
  {
    id: 'freelance',
    role: 'Web Developer',
    company: 'Freelance',
    period: 'October 2023 — April 2025',
    current: false,
    responsibilities: [
      'End-to-end client website development, from interface design in Figma to development and database handling.',
      'Team coordination for e-commerce, optical store sales, and travel / bus reservation projects.',
    ],
    projectSlugs: ['freelance-ecommerce', 'optical-store-system', 'travel-bus-reservation'],
  },
  {
    id: 'satu-visi',
    role: 'Web Developer',
    company: 'PT Satu Visi Digital',
    period: 'June 2022 — October 2023',
    current: false,
    responsibilities: [
      'Work on the Stylease branded clothing rental platform.',
      'Book-data website for Galeri SBY-ANI Library in Pacitan, including technical support and data-entry troubleshooting.',
    ],
    projectSlugs: ['stylease', 'galeri-sby-ani-library'],
  },
  {
    id: 'inti',
    role: 'Web Developer Intern',
    company: 'PT Industri Telekomunikasi Indonesia',
    period: 'January 2021 — March 2021',
    current: false,
    responsibilities: ['Development of a tourism profile website.'],
    projectSlugs: ['tourism-profile-website'],
  },
]
export const suggestedSearches: SuggestedSearch[] = [
  { query: 'ACS', label: 'ACS attendance integration' },
  { query: 'WMS', label: 'Warehouse management' },
  { query: 'NestJS', label: 'NestJS' },
  { query: 'Laravel', label: 'Laravel' },
  { query: 'freelance', label: 'Freelance work' },
  { query: 'AI debugging', label: 'AI-assisted development' },
  { query: 'Ecovia', label: 'Ecovia' },
  { query: 'Stylease', label: 'Stylease' },
]
export const navigation = [
  { label: 'About', to: '/about', icon: 'user' },
  { label: 'Projects', to: '/projects', icon: 'folder' },
  { label: 'Skills', to: '/skills', icon: 'code' },
  { label: 'Experience', to: '/experience', icon: 'briefcase' },
  { label: 'Contact', to: '/contact', icon: 'mail' },
]
